# golangci-lint configuration
run:
  timeout: 2m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "Error return value of `w.Write` is not checked"
    - "Error return value of `.*json.Encoder.*.Encode` is not checked"
    - "Error return value of `.*ListenAndServe.*` is not checked"
